name = "tobira-video-proxy"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

account_id = "349d1bc326ebd8f64abfe827fa61ade4"
workers_dev = true
preview_urls = true

routes = [
  { pattern = "video.tobira.app", custom_domain = true }
]

[observability]
enabled = true
