import sanitizeHtml from "sanitize-html";

const SVG_TAGS = [
  "svg",
  "g",
  "defs",
  "symbol",
  "title",
  "desc",
  "path",
  "circle",
  "ellipse",
  "line",
  "polyline",
  "polygon",
  "rect",
  "text",
  "tspan",
  "linearGradient",
  "radialGradient",
  "stop",
  "clipPath",
  "mask",
  "pattern",
  "filter",
  "feBlend",
  "feColorMatrix",
  "feComposite",
  "feDropShadow",
  "feFlood",
  "feGaussianBlur",
  "feMerge",
  "feMergeNode",
  "feOffset",
  "feSourceGraphic",
];

const SVG_ATTRIBUTES = [
  "aria-hidden",
  "aria-label",
  "class",
  "clip-path",
  "clip-rule",
  "color",
  "cx",
  "cy",
  "d",
  "dx",
  "dy",
  "fill",
  "fill-opacity",
  "fill-rule",
  "filter",
  "font-family",
  "font-size",
  "font-weight",
  "height",
  "id",
  "mask",
  "offset",
  "opacity",
  "points",
  "preserveAspectRatio",
  "r",
  "role",
  "rx",
  "ry",
  "spreadMethod",
  "stop-color",
  "stop-opacity",
  "stroke",
  "stroke-dasharray",
  "stroke-dashoffset",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-miterlimit",
  "stroke-opacity",
  "stroke-width",
  "transform",
  "viewBox",
  "width",
  "x",
  "x1",
  "x2",
  "xmlns",
  "y",
  "y1",
  "y2",
];

export function sanitizeSvgBuffer(bytes: Buffer) {
  const sanitizedSvg = sanitizeHtml(bytes.toString("utf-8"), {
    allowedTags: SVG_TAGS,
    allowedAttributes: {"*": SVG_ATTRIBUTES},
    allowedSchemes: [],
    allowProtocolRelative: false,
    disallowedTagsMode: "completelyDiscard",
    parseStyleAttributes: false,
    parser: {lowerCaseAttributeNames: false, lowerCaseTags: false},
    selfClosing: ["circle", "ellipse", "line", "path", "polygon", "polyline", "rect", "stop"],
  });

  return Buffer.from(sanitizedSvg, "utf-8");
}
